apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeeye-agent.fullname" . }}
  labels:
    {{- include "nodeeye-agent.labels" . | nindent 4 }}
type: Opaque
data:
  agent-token: {{ .Values.agentToken | b64enc | quote }}
